name: Deploy Contoso_University_Core

on:
  workflow_run:
    workflows: ["Pack Contoso_University_Core"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: test
    steps:
      - uses: dawidd6/action-download-artifact@v4
        with:
          workflow: pack-solution.yml
          name: packed-solution
      - uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: https://jflores-build.crm.dynamics.com/
          app-id: ${{ secrets.APPLICATIONID }}
          client-secret: ${{ secrets.SECRETKEY }}
          tenant-id: ${{ secrets.TENANT }}
          solution-file: contoso_university_core_managed.zip
